[package]
name = "aurorae-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
aurorae-core = { path = "../aurorae-core" }

# Dépendances de base pour l'IA
ndarray = { version = "0.15", features = ["serde"] }
tch = { version = "0.13.0", optional = true }
rust-bert = { version = "0.21", optional = true }
linfa = { version = "0.7", optional = true }

[features]
core = []
full = ["tch", "rust-bert", "linfa"]
neuromorphic = ["full"]
