[package]
name = "aurorae-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
aurorae-core = { path = "../aurorae-core" }

# Écosystème Solana avec ses propres dépendances
solana-sdk = "1.17.17"
solana-program = "1.17.17"
anchor-lang = "0.29"
# Épingler zeroize à la version compatible avec Solana
zeroize = "=1.3.0"
# ... autres dépendances Solana
