// Modules principaux
pub mod guardian;
pub mod economy;
pub mod dream;
pub mod alchemy;
pub mod deployer;
pub mod nft_minter;
pub mod autonomy;
pub mod validator;
pub mod founder_income;
pub mod blockchain_core;
pub mod evolution;
pub mod intelligence;
pub mod security;
