[package]
name = "aurorae-core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Utilitaires essentiels sans conflits
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
uuid = { version = "1.7", features = ["v4", "serde"] }
rand = { version = "0.8", features = ["small_rng"] }
sha2 = "0.10"
thiserror = "1.0"
anyhow = "1.0"
# ... autres dépendances communes
