[package]
name = "aurorae-polkadot"
version = "0.1.0"
edition = "2021"

[dependencies]
aurorae-core = { path = "../aurorae-core" }

# Écosystème Polkadot avec ses propres dépendances
polkadot-sdk = "2503.0.1"
substrate-api-client = "0.17"
# Utiliser la version de zeroize dont polkadot-sdk a besoin
zeroize = "1.7.0"
# ... autres dépendances Polkadot
