[package]
name = "aurorae-eth"
version = "0.1.0"
edition = "2021"

[dependencies]
aurorae-core = { path = "../aurorae-core" }

# Écosystème Ethereum
ethers = { version = "2.0.14", features = ["legacy", "abigen"] }
k256 = "0.13.1"
# ... autres dépendances Ethereum
